### ISSUE TITLE
Doesn't compile on macOS 

### ISSUE THREAD

**Issue by mttbernardini** [mebeim/minibench#1] opened 2022-08-24 07:40 UTC
The program fails to compile on macOS due to missing declaration of `wait4`, which is not exposed in [`<sys/wait.h>`](https://fergofrog.com/code/cbowser/xnu/bsd/sys/wait.h.html#254-257) unless the macro `_POSIX_C_SOURCE` is undefined or the macro `_DARWIN_C_SOURCE` is defined.

```sh
$ make
cc -std=c99 -O3 -Wall -Wextra -pedantic -pedantic-errors -o bench bench.c -Wl,-z,relro,-z,now -lm
bench.c:417:9: error: implicit declaration of function 'wait4' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        while (wait4(child_pid, &child_status, wait_flags, rusage) == (pid_t)-1) {
               ^
bench.c:417:9: note: did you mean 'wait'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:9: note: 'wait' declared here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
        ^
1 error generated.
make: *** [bench] Error 1
```

```sh
$ cc -v
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by mebeim** [comment] 2022-08-24 14:14
Damn, I knew that `wait4` was going to be a silly compatibility issue :'). Don't have an environment to test on, but check if the issue is fixed on the `macos` branch I just pushed.

**Comment by mttbernardini** [comment] 2022-08-24 14:21
🤔 

```sh
cc -std=c99 -O3 -Wall -Wextra -pedantic -pedantic-errors -o bench bench.c -Wl,-z,relro,-z,now -lm
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bench] Error 1
```

**Comment by mebeim** [comment] 2022-08-24 14:46
Well TIL the linker for macOS does not know about `-z`, interesting. The `Makefile` should take care of that now, try again.

**Comment by mttbernardini** [comment] 2022-08-24 14:59
Compiles and runs, however `strip` fails:

```sh
cc -std=c99 -O3 -Wall -Wextra -pedantic -pedantic-errors -o bench bench.c -lm
strip -R.comment bench
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: unrecognized option: -R.comment
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip [-AnuSXx] [-] [-d filename] [-s filename] [-R filename] [-o output] file [...] 
make: *** [bench] Error 1
```

I think `strip` doesn't support removing sections in Darwin:

```
$ man strip
[...]
-R filename
       Remove the symbol table entries for the global symbols listed in
       filename.  This file has the same  format  as  the  -s  filename
       option  above.   This option is usually used in combination with
       other options that save some symbols, -S, -x, etc.
[...]
```

**Comment by mebeim** [comment] 2022-08-24 15:29
Oh my god Apple give me a break LOL. I guess let's prefer compatibility over stripping a silly section. Also funny that it's interpreting `-R.comment` as a single option and not option plus value, otherwise the error would be different. Now just gotta hope `install` works as expected :crossed_fingers:

**Comment by mttbernardini** [comment] 2022-08-24 15:31
yup, works fine now (including `install`)

**Comment by mebeim** [comment] 2022-08-24 15:33
Amazing, merging these changes then. Thanks for the help!

**Closed as completed by mebeim** 2022-08-24 15:33 UTC
